### ISSUE TITLE
Trigger the change of music by Content/TargetUpdated

### ISSUE THREAD

**Issue by 3XistencE** [joyrider3774/PlayniteSound#1]
I notice that the plugin doesn't get triggered if the user switch between games when is in Fullscreen Game Details.
The problem is noticeable after the selection of a game (without launching it from the list) and by entering the Game Details View.
By switching to another game (can be done by gamepad LB/RB triggers on a controller or F2/F3 keys on keyboard)

Expected behaviour: Change music as the Content/Game Change
What happend instead: Still play the music of the first watched game in Game Details View (accessible from the Main List of Game, press the A button in Fullscreen mode)

**Comment by joyrider3774** [comment]
sorry for late reply, did not notice this. The problem was / is actually a playnite bug which will be fxed in playnite 9 see https://github.com/JosefNemec/Playnite/issues/2268
