### ISSUE TITLE
(Enhancement) Add sound support for more click events

### ISSUE THREAD

**Issue by ATNewHope** [joyrider3774/PlayniteSound#10]
Now, the extension gives user some kind of clicking feedback and sure improves the experience.
However, the only click event supported is game selection.
it's not enough comparing to other game UI, such as Steam's big picture mode. (Though, Steam won't let you DIY the sound which is not cool as this extension)

**Comment by joyrider3774** [comment]
i can only add events for events that are exposed by the plugin system and thats whats already happening
