### ISSUE TITLE
[Request] Silence Background music when enabling Video sound.

### ISSUE THREAD

**Issue by cnapolit** [joyrider3774/PlayniteSound#11]
Currently, when using extra metadata (fullscreen loader) and the right theme, both the background and video audio will play if enabled.
It would be nice if the background music could pause when a video is playing with audio.

**Comment by joyrider3774** [comment]
i have no control over other extensions so i can not detect if video is playing or not

**Comment by cnapolit** [comment]
Yeah, I figured it would require modification to other themes, but I figured it was worth asking. Thanks for the reply!
