### ISSUE TITLE
[Request] Integration with KHInsider

### ISSUE THREAD

**Issue by cnapolit** [joyrider3774/PlayniteSound#12]
One of the more reliable ways to mass download may be KHInsider. This [script](https://github.com/obskyr/khinsider) with a slight modification to grab the first file in the album could be a way to do that. Tagging any entries that fail would probably be a good idea too.

Thanks for making this extension in the first place!

**Comment by cnapolit** [comment]
I have a half-finished implementation of this here: https://github.com/cnapolit/PlayniteSound
Reached out to the site owner, who warned of DMCA risk, so that's always fun....
Edit: annnddd it's probably too big a risk legally. Oh well, it was fun learning about.

**Comment by joyrider3774** [comment]
@cnapolit what as the DMCA about ? playnite sounds downloading the music from khinsder and they not liking that ? if so i don't want it to be added
