### ISSUE TITLE
does not work on playnite 9

### ISSUE THREAD

**Issue by zany130** [joyrider3774/PlayniteSound#4]

**Comment by joyrider3774** [comment]
won't be updated

**Comment by joyrider3774** [comment]
Seems too many people are requesting this so i'll try to make a version for playnite 9 during weekend

**Comment by joyrider3774** [comment]
already made a version should be available soon on build in browser if it gets accepted, in the mean time you can download from here

https://github.com/joyrider3774/PlayniteSound/releases/latest
