### ISSUE TITLE
Dependencies to port personally to Playnite 9

### ISSUE THREAD

**Issue by SuperJayRay** [joyrider3774/PlayniteSound#5]
Hello, I'd like to port this to Playnite 9 myself cause I heard it won't be updated. The built  Just wanted to know if there are any special dependencies/things that will not work (besides Playnite SDK version).

**Comment by joyrider3774** [comment]
the reference should still be in the project. But you need todo more than just updating the playnite sdk version especially with things related to platform(s)

**Comment by joyrider3774** [comment]
i'll port it myself during weekend seems too many people won't update to playnite 9 because of this extension not existing
