### ISSUE TITLE
Setting to pause/resume background music if Playnite is minimized/in-focus

### ISSUE THREAD

**Issue by xBitsoft** [joyrider3774/PlayniteSound#6]
Please add an option under settings to pause the background music when Playnite is minimized and resume when Playnite is back in focus. Ideally the music should just be paused and not be completely stopped, and then unpaused from where it left off again.

**Comment by snackerfork** [comment]
I very, very much would want this feature and came here to request it. I love the idea of the background music and it's great in Fullscreen mode but having no way to automatically pause it when I switch to a different window is pretty annoying.

**Comment by joyrider3774** [comment]
Hey i just released a new version with this option implemented
