### ISSUE TITLE
Request for the currently playing music's tag data to be exposable strings and useable by themes.

### ISSUE THREAD

**Issue by SugarSpikes** [joyrider3774/PlayniteSound#63]
Hi there! I use PlayniteSounds to play a variety of video game remixes in my theme. I would love to be able to display the currently playing music's tag data in my theme; Just the basics, song name, artist, and album to be available and usable as individual string data, which a theme could incorperate.

**Comment by cnapolit** [comment]
Apologies for the late reply. Sounds doable, I can include it as part of #40.

**Comment by cnapolit** [comment]
Closing as duplicate
