### ISSUE TITLE
Have an option for fullscreen mode that plays game music only once the game has been selected

### ISSUE THREAD

**Issue by Meiloorun** [joyrider3774/PlayniteSound#65]
It would be good if there were an option for the fullscreen mode that will play the game music only when the game is selected and not just when hovering over the game. This is useful because, the fullscreen theme I am using plays background music for the menu, so the two different music are overlapping. It would be good if the music played only once the game has been selected, like the Wii Menu.

**Comment by cnapolit** [comment]
Surprised I don't seem to have an explicit item for this.
I have something like this working, but it needs a more proper implementation to be included in any release.
