### ISSUE TITLE
Sound keeps playing for 1-2 more seconds

### ISSUE THREAD

**Issue by WilliamLeGod** [joyrider3774/PlayniteSound#8]
Is there anyway to fix the sound delay turn off when starting a game? In the video the sound keeps playing for 1-2 seconds after I press start game and splash screen already shows up for 1-2 sec

https://user-images.githubusercontent.com/70202711/147711859-f7f94a36-1eca-4f62-bd50-b8c95ad77289.mov

**Comment by joyrider3774** [comment]
check for updated version 4.4, i Added option to choose when music stops (game is starting  / game has started)
